notifications:
  email: false

language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - g++-4.9
            - clang-3.6
      env: COMPILER=clang++-3.6

before_install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt562-trusty
 - sudo apt-get update -qq

install:
 - sudo apt-get install qt56base qt56webengine valgrind

script:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
 - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
 - . /opt/qt56/bin/qt56-env.sh
 - qmake QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_CXXFLAGS+="-g" QMAKE_CFLAGS+="-g" QMAKE_LINK=g++-4.9 CONFIG+=nowebengine
 - make -j2
 - valgrind --run-libc-freeres=no ./acquisition --test -platform offscreen
