image: Visual Studio 2017

install:
  - git submodule update --init deps/boost-header-only

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - C:\Qt\5.9.1\msvc2017_64\bin\qmake.exe -tp vc
